# Generated by Django 3.2.16 on 2023-01-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_profession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Професcия', 'verbose_name_plural': 'Профессии'},
        ),
    ]
